#!/bin/bash
# Custom ruleset on top of --standard="~/.composer/vendor/drupal/coder/coder_sniffer/Drupal".
~/.composer/vendor/bin/phpcs --standard="~/drustalls/fpfis_custom_ruleset.xml" --extensions="php,info,module,inc,install,test,profile,theme,js,css" "$@"
