<?php
/**
 * @file
 * Code for the Dev feature.
 * https://www.lullabot.com/blog/article/quick-and-dirty-debugging
 */

include_once 'dev.features.inc';

//tail –f my_log.txt
function log_to_file($text) {
  $f = fopen('my_log.txt', 'a');
  fwrite($f, date('Ymd H:i:s - ') . $text . "\n");
  fclose($f);
}


/**
 * @param $msg
 *
 */
function msgvar($msg=null){
  if (function_exists('dsm')) {
    dsm($msg);
  }
  elseif(is_array($msg) || is_object($msg)){
    drupal_set_message('<pre>'.print_r($msg,true).'</pre>');
  }
  else{
     drupal_set_message( check_plain($msg));
  }
}
